### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by caferyrk** [FriendsOfShopware/FroshPlatformMailArchive#16]
Hello everyone,

for a new SW6 project, we want to use your plugin. We are working on the 6.4.0.0 Shopware version. I was able to install your plugin on our staging, however the following error appears during activation:

"Internal Server Error" - I have sent you that the error message also attached once. Is it an error that can be fixed on our part or plugin dependent?

Thank you for your help, I look forward to your feedback.

![Bildschirmfoto 2021-05-20 um 13 23 32](https://user-images.githubusercontent.com/84894301/119772885-25ac9e00-bec0-11eb-91a3-36925041d4df.png)

**Comment by shyim** [comment]
Do you use 0.3.0?

**Comment by caferyrk** [comment]
I used the 0.2.2 Version. With the 0.3.0 version it runs now. Thank you for your advice!
