### ISSUE TITLE
Cleanup task for older mails

### ISSUE THREAD

**Issue by zolthan** [FriendsOfShopware/FroshPlatformMailArchive#18]
Having this plugin installed over several months it would be nice to have some kind of cleanup process implemented. Even for DSGVO purposes it would be nice to be able to keep archived mails just for X days or months.

**Comment by zolthan** [comment]
OK, this seems to get an issue. After having installed the plugin for more than a year, the archive table is several GB big. @shyim do you think the cleanup will be implemented?

**Comment by shyim** [comment]
Hey,

What do you mean with archived? I would just delete them 🤔

**Comment by zolthan** [comment]
Sure just delete them. What I mean is the `frosh_mail_archive`-Table 😂

**Comment by shyim** [comment]
Does this solve your issue? https://github.com/FriendsOfShopware/FroshPlatformMailArchive/commit/411bc63759fac55b7d24768117505bc6bf6f48b8

**Comment by zolthan** [comment]
Hi @shyim , looks pretty good. Will you build a Release for this? Thanks a lot!

**Comment by shyim** [comment]
https://github.com/FriendsOfShopware/FroshPlatformMailArchive/releases/tag/0.3.1
