### ISSUE TITLE
Shopware 6.4.4.1 mails no longer displayed "neterror"

### ISSUE THREAD

**Issue by artdevil-de** [FriendsOfShopware/FroshPlatformMailArchive#19]
### PHP Version

8.0.10

### Shopware Version

6.4.4.1

### Actual behaviour

Clicking on an email in the plugin, opens the individual mail page.
on that page, the "HTML" and "PLAIN" no longer show the body of the mail, they show "neterror" instead.

Plugin 0.3.1

### Expected behaviour

the mail body should be shown, in html and in plain

### Steps to Reproduce?

Install latest Shopware Update 6.4.4.1, under 6.4.4.0 the mail body was shown

**Comment by shyim** [comment]
Tested works without issues

**Comment by artdevil-de** [comment]
Looks like our admin overshot with securing the server. 
A CSP got in the way,
I confirm, plugin working under Shopware 6.4.4.1
