### ISSUE TITLE
MailArchive not shown in menu

### ISSUE THREAD

**Issue by handmeatowel** [FriendsOfShopware/FroshPlatformMailArchive#20]
### PHP Version

7.4.25

### Shopware Version

v6.4.6.0

### Actual behaviour

Plugin installed and activated, cache cleared > menu not shown in backend

### Expected behaviour

MailArchive shows in menu

### Steps to Reproduce?

Installation as described in plugin

**Comment by shyim** [comment]
It should be under Settings -> Extensions

**Comment by handmeatowel** [comment]
Unfortunately it isn't.

**Comment by shyim** [comment]
how did you installed it?

**Comment by handmeatowel** [comment]
Via the zipped release file

**Comment by handmeatowel** [comment]
Anything I can help with getting this to work?

**Comment by shyim** [comment]
You used this zip oder? https://github.com/FriendsOfShopware/FroshPlatformMailArchive/releases/download/0.3.1/FroshPlatformMailArchive.zip

**Comment by handmeatowel** [comment]
I used the one available from the releases, the link there is https://github.com/FriendsOfShopware/FroshPlatformMailArchive/archive/refs/tags/0.3.1.zip, it's probably the same as the one you mentioned.

**Comment by shyim** [comment]
The tag doesn't contain compiled files. Try mine link

**Comment by handmeatowel** [comment]
That was it. Thanks a lot!
