### ISSUE TITLE
Löschen älterer Mail

### ISSUE THREAD

**Issue by cbmod21** [FriendsOfShopware/FroshPlatformMailArchive#22]
### Question

Da die Datenbank langsam sehr groß wird (2gb nur mailarchive) meine Frage:
Können ältere Mails einfach aus der Datenbank gelöscht werden oder führt das zu einen Fehler im Shopware-Backend.

In der neuen Plugin-Version gibt es ja auch schon eine Löschfunktion. Hier wäre noch eine Einstellung nach Datum schön.
Also: "Alle Mails älter als 1.10.21 löschen"

Danke für Eure Hilfe und das wirklich gute Plugin.

sg,
Christian

**Comment by artdevil-de** [comment]
Hallo Christian,
schau doch einfach mal in die Konfiguration von dem Plugin, dort findest Du die Einstellung "Nachrichten nach x Tagen löschen
" womit Du steuern kannst ab welchem Alter der cronjob die archivierten Mails löschen soll.
Wenn Du nichts an den Einstellungen bisher vorgenommen hast, steht es im Standard auf 90 Tage.

Ich hoffe ich konnte Dir damit helfen.

Das Ticket kann in meinen Augen geschlossen werden, da es die gewünschte Funktion schon gibt.
