### ISSUE TITLE
Emails in BCC

### ISSUE THREAD

**Issue by gentisheholli** [FriendsOfShopware/FroshPlatformMailArchive#25]
### Please describe the feature you would like to see implemented.

Hi,
Is there any possibility that we get the mails in BCC instead of a separate mail? 
If not, are you planning on doing such a feature?

Best Regards,

**Comment by tinect** [comment]
Hi,

The task of this plugin is to save sent mails into database to be searchable afterwards.
That is the reason why this is no feature which relates to the task.

I don't know such a feature in shopware yet, but there are plugins in store advertising such feature.

I'm sorry we cannot help you with this :-(

Best Regards,
Sebastian
