### ISSUE TITLE
Shopware 6.4.10 breaks plugin

### ISSUE THREAD

**Issue by artdevil-de** [FriendsOfShopware/FroshPlatformMailArchive#26]
### PHP Version

8.0.17

### Shopware Version

6.4.10

### Actual behaviour

Link under Settings > Extensions is missing

Direct call of /admin#/frosh/mail/archive/list  results in a white page

### Expected behaviour

Link should be available & plugin should work

### Steps to Reproduce?

update from Shopware 6.4.9 where everything was working fine to Shopware 6.4.10 which breakes this plugin

**Comment by artdevil-de** [comment]
Just for quick confirmation,
I am running version 0.3.1 and a reinstall did not help.

**Comment by tinect** [comment]
Thank you.
Please check recent version.

**Comment by artdevil-de** [comment]
Confirmed, new version fixes the problem.
Thanks for the swift solution
