### ISSUE TITLE
plugin is missing in the menu

### ISSUE THREAD

**Issue by spacenavigation** [FriendsOfShopware/FroshPlatformMailArchive#29]
### PHP Version

7.4.16

### Shopware Version

6.4.10.1

### Actual behaviour

Plugin installed, activated and it's not showing up in the SW-menu

### Expected behaviour

showing up in the SW-menu to see the mail archive

### Steps to Reproduce?

Plugin installed and activated. Even deleted and reinstalled, but same issu
<img width="1339" alt="mail-archive-shopware" src="https://user-images.githubusercontent.com/105081314/167212139-f65749f4-6a66-4293-9ffa-0a75ec592bfd.png">
e

**Comment by tinect** [comment]
Hey @spacenavigation 

Which "SW-menu" do you mean?

Here is the position of the menu 🤔 
![image](https://user-images.githubusercontent.com/135993/167250603-6b43e0d7-9f70-40cd-8ec9-c6b29a534313.png)

**Comment by shyim** [comment]
maybe that shitty compile issue that we need to compile on newer shopware version so its working everywhere

**Comment by spacenavigation** [comment]
Hi tinec, and thanks for taking care of the report
i must apologize, i was fixated on the image / screenshot in the detailed description of the plugin and didn't get the idea to search in the settings menu
![phpj8iApH](https://user-images.githubusercontent.com/105081314/167254285-c667223d-d0cd-4a79-96e2-d7adaff88377.png)

**Comment by tinect** [comment]
@shyim it is dixed in current plugin version

@spacenavigation so you found it now? 

We will update the image :-)
