### ISSUE TITLE
Wo starten

### ISSUE THREAD

**Issue by happygreens** [FriendsOfShopware/FroshPlatformMailArchive#38]
### Question

Hallo

wo starte ich Ihr Plugin?
Bei Ihnen steht "Meine Erweiterungen > Mailarchiv" aber da ist kein Menüpunkt...
aktiviert für alle kanäle ist es....

Gruß, Mario Berg

shopware 6.2.1.
testshop: mond.tv

**Comment by stefanpoensgen** [comment]
Einstellungen -> Erweiterungen -> Mail Archiv
