### ISSUE TITLE
Datenschutzhinweise und Nutzungsbedingungen

### ISSUE THREAD

**Issue by SilkeVogel** [FriendsOfShopware/FroshPlatformMailArchive#39]
### Question

Guten Tag,

wir möchten gerne Ihr Plugin "Mail Archive" in unseren Shopware-Shop integrieren. Können Sie mir sagen, wo die Daten aus dem Plugin gehostet werden? Haben die Programmierer/Hersteller Zugriff auf das Plugin und die darin enthaltenen Daten? Gibt es vielleicht Datenschutzhinweise und/oder Nutzungsbedingungen?

Vielen Dank und beste Grüße
Silke Höffken

**Comment by stefanpoensgen** [comment]
Die Daten werden in der Shopware Datenbank gespeichert. Es gibt vom Datenschutz her keine zusätzlichen Dinge zu beachten.

**Comment by SilkeVogel** [comment]
Vielen Dank für Ihre schnelle Rückmeldung.

Könnten Sie mir noch sagen, ob dies für alle Ihre Shopware-Plugins gilt?

Vielen Dank und beste Grüße
Silke Höffken

Von: Stefan Poensgen ***@***.***>
Gesendet: Montag, 6. Februar 2023 11:58
An: FriendsOfShopware/FroshPlatformMailArchive ***@***.***>
Cc: Höffken Silke ***@***.***>; Author ***@***.***>
Betreff: Re: [FriendsOfShopware/FroshPlatformMailArchive] Datenschutzhinweise und Nutzungsbedingungen (Issue #39)

Sie erhalten nicht oft eine E-Mail von ***@***.*** Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>

Die Daten werden in der Shopware Datenbank gespeichert. Es gibt vom Datenschutz her keine zusätzlichen Dinge zu beachten.

-

**Comment by shyim** [comment]
Es ist alles nur lokal in der Shopware Instanz. Es muss nichts für Datenschutz beachtet werden

**Comment by SilkeVogel** [comment]
Vielen Dank für die Information!

Mit besten Grüßen
Silke Höffken

Von: Shyim ***@***.***>
Gesendet: Dienstag, 10. September 2024 14:06
An: FriendsOfShopware/FroshPlatformMailArchive ***@***.***>
Cc: Höffken Silke ***@***.***>; Author ***@***.***>
Betreff: Re: [FriendsOfShopware/FroshPlatformMailArchive] Datenschutzhinweise und Nutzungsbedingungen (Issue #39)

Sie erhalten nicht oft eine E-Mail von ***@***.*** Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>

Es ist alles nur lokal in der Shopware Instanz. Es muss nichts für Datenschutz beachtet werden
