### ISSUE TITLE
No update possible from 1.0.0 to 1.01/2.0.0 

### ISSUE THREAD

**Issue by pfeitim** [FriendsOfShopware/FroshPlatformMailArchive#46]
### Question

Hello, 

i just found out, that there is a missing dependency for my update, so no update at all is possible from 1.0.0 to 1.01 nor 2.0.0, what am I doing wrong? 

<img width="381" alt="image" src="https://github.com/FriendsOfShopware/FroshPlatformMailArchive/assets/16204467/b389aa7c-f04e-4fad-aeca-974c7cfb026f">

**Comment by pfeitim** [comment]
I have deinstalled the plugin and then added zbateson/mail-mime-parser but the plugin cannot be installed anymore. 

<img width="1213" alt="image" src="https://github.com/FriendsOfShopware/FroshPlatformMailArchive/assets/16204467/cfd07f33-8826-4eb7-b2c1-7df43e54cdda">

**Comment by pfeitim** [comment]
I have deinstalled the plugin and then added zbateson/mail-mime-parser via composer, then re-installed the plugin. 

Now it works. However, this should not be the right way for Shopware beginners without programming/server experience.  

In Shopware-Root via SSH: **composer require zbateson/mail-mime-parser**

<img width="1219" alt="image" src="https://github.com/FriendsOfShopware/FroshPlatformMailArchive/assets/16204467/bece2ea0-0d7d-4493-b6e4-11a94fedb445">

**Comment by pfeitim** [comment]
After reinstalling there was a message that I should run:
bin/console frosh:mailarchive:migrate

However this generated an UTF-8 error:

<img width="1227" alt="image" src="https://github.com/FriendsOfShopware/FroshPlatformMailArchive/assets/16204467/078bd329-b44a-43e8-93e4-b5f92c9abbf5">

**Comment by tinect** [comment]
The installation of zbateson/mail-mime-parser should be fixed with version 2.0.1.

Can you get the EML from the database of the entry which is failing?

**Comment by tinect** [comment]
@pfeitim fixed with 2.0.2

Thank you for the report.

**Comment by pfeitim** [comment]
@tinect 

Migration ran successfully, but the message in the Shopware backend remains that one should please migrate. I migrated this morning, 6 hours later the message is still there. Not sure if it's just caching the error message...

**Comment by pfeitim** [comment]
@tinect 

We are actually having a problem with the message queue right now. Somehow there are heaps of entries that don't leave. I have given it to our server contact person.

But in general I think that's the reason. Thank you and sorry for not seeing before.

**Comment by tinect** [comment]
No problem :-) You are welcome.
