### ISSUE TITLE
Mail Archive 2.0.0 Bug

### ISSUE THREAD

**Issue by Marco-Innocent** [FriendsOfShopware/FroshPlatformMailArchive#47]
### Shopware Version

6.5.4.0

### Actual behaviour

Can't install the updated version 2.0.0. I also uninstalled the plugin but still can't install the new version. I get following error message:

**Failed Dependency**

Required plugin/package "zbateson/mail-mime-parser ^2.4" is missing or not installed and activated"

Before everything worked fine!?

Best regards,
Marco

### Expected behaviour

Should install without an error.

### Steps to Reproduce?

n.a.

**Comment by shyim** [comment]
Is fixed with 2.0.1
