### ISSUE TITLE
How/where to run the command "bin/console frosh:mailarchive:migrate"?

### ISSUE THREAD

**Issue by phillipmohr** [FriendsOfShopware/FroshPlatformMailArchive#50]
### Question

Hello, after updating Mail Archive plugin and Shopware we got prompted to migrate the mails: "CLI with the command:
bin/console frosh:mailarchive:migrate". 

1. logged in via SSH
2. ran "./bin/console frosh:mailarchive:migrate" within the project folder (parent folder of "bin")
3. Error message: There are no commands defined in the "frosh:mailarchive" namespace.  

In which folder do I need to run the command? 

Shopware version: 6.5.4.1 
Mail Archive Plugin version: 2.0.3

Thank you

**Comment by shyim** [comment]
Can you run once cache clear and look if it's then there?

**Comment by phillipmohr** [comment]
@shyim Yes I ran the command cache:clear and also cleared the cache from the backend but unfortunately it doesn't work. I can't see any `frosh` command when I run `./bin/console` 

I wanted to try plugin:refresh as well but this gives me another weird error. 

```
02:23:34 CRITICAL  [console] Error thrown while running command "plugin:refresh". Message: "An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory" ["exception" => Doctrine\DBAL\Exception\ConnectionException^ { …},"command" => "plugin:refresh","message" => "An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory"]

In ExceptionConverter.php line 101:
                                                                                         
  An exception occurred in the driver: SQLSTATE[HY000] [2002] No such file or directory  
                                                                                         

In Exception.php line 28:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

In Driver.php line 34:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
```

**Comment by shyim** [comment]
Your basic shopware installation is not working. it cannot connect to the database for some reason

**Comment by tinect** [comment]
Due to inactivity, we assume you resolved the issue. So we will close here.
