### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by OH-Platinium** [FriendsOfShopware/FroshPlatformMailArchive#53]
### PHP Version

8.1.22

### Shopware Version

6.5.5.1

### Actual behaviour

After updating to Shopware 6.5.5.1 from 6.4.20.1 there was the following error message:

Required plugin/package "zbateson/mail-mime-parser ^2.4" is missing or not installed and activated

Then I entered the following command: "composer require zbateson/mail-mime-parser" but there was no improvement.

### Expected behaviour

The update automatically installs the required packages

### Steps to Reproduce?

Install the package on a standard “all-inkl (all-inkl.com)” server with Shopware 6.5 installed. Alternatively, a server without the mail-mime-parser 2.4 package is also possible

**Comment by tinect** [comment]
Which version did you install?
And how did you install (composer, store, zip, ....)? Please describe the steps you did.

**Comment by OH-Platinium** [comment]
MailArchive Version: 2.0.4

I saw that I didn't execute the command in the Shopware directory.

I can now install zbateson/mail-mime-parser. The Composer.json says he has 2.4 installed.

Meanwhile he gives the following error message when activating the extension (mail archive):

```
Internal Server Error
Cannot autowire service "Frosh\MailArchive\Services\MailSender": argument "$mailSender" of method "__construct()" references class "Shopware\Core\Content\Mail\Service\AbstractMailSender" but no such service exists. You should maybe alias this class to one of these existing services: "Shopware\Core\Content\Mail\Service\MailSender", "Frosh\MailArchive\Services\MailSender".
```

It would be nice if MailArchive could install the zbateson/mail-mime-parser extension independently.

**Comment by tinect** [comment]
mine-parser is veing instaöled on default installations, depending on how you installed the plugin afterwards. did you deactivate the plugin before upgrading?
how did you install the plugin?

we will check the autowire problem next days.

**Comment by OH-Platinium** [comment]
Ich habe alle erweiterungen vor dem Update deaktiviert.

Das Plugin habe ich über den Shop installiert

**Comment by tinect** [comment]
what do you mean with shop?
administration of your shop? the shopware store?

Please tell us the steps you performed.

**Comment by OH-Platinium** [comment]
After the update to Shopware 6.5, I tried to install the update via the admin area (www.meine-domain.de/admin + Extensions->My Extensions). The error message came from above. Then I downloaded it from https://account.shopware.com/ and tried to install it via "Extensions->My Extensions->Upload Extension". It didn't work either. I then uninstalled Mail Achive and installed it via the admin area and again via Upload Extension. Always with the same result. Error message: Required plugin/package "zbateson/mail-mime-parser ^2.4" is missing or not installed and activated

Then I went into the console and executed: composer require zbateson/mail-mime-parser in the Shopware directory. The update from Mail Archive could then be installed. When activating, the following error message appears: "Internal Server Error
Cannot autowire service "Frosh\MailArchive\Services\MailSender": argument "$mailSender" of method "__construct()" references class "Shopware\Core\Content\Mail\Service\AbstractMailSender" but no such service exists. You should maybe alias this class to one of these existing services: "Shopware\Core\Content\Mail\Service\MailSender", "Frosh\MailArchive\Services\MailSender"."

**Comment by OH-Platinium** [comment]
Can you tell me which tables in the database the plugin accesses? I just had a flash of inspiration that maybe something wasn't right there.

During my first failed attempt to update to Shopware 6.5, it did not restore the “pickware_shipping_shipping_method_config” table correctly from the backup. There was an error in the collation column. I fixed this manually. Maybe it's similar with this plugin, only that I didn't get an error message when restoring the database.

The database error was the following:
`d03xxx1`.`pickware_shipping_shipping_method_config` cannot be generated (Error: 150 "Foreign key constraint is incorrectly formed")

Maybe you can reproduce the error. If the following plugins are still installed.

     Theme STRATUS | Per
     Customizable Popups & Notifications - Version: 2.0.0
     PayPal for Shopware 6 - Version: 7.2.2
     DHL Shipping - Version: 2.0.1
     Blog Modules - Version: 2.0.2

**Comment by tinect** [comment]
The plugin accesses any table stating with `frosh_mail`.
I cannot reproduce the error. You might want to check with an experienced developer, what is causing these errors on your system.

**Comment by OH-Platinium** [comment]
thanks for the help so far.

Unfortunately nothing helped. I uninstalled the plugin. The two tables were deleted in the database and then uninstalled using composer zbateson/mail-mime-parser ^2.4.

Now when I want to install the plugin I get the error message:

Failed dependency

Required plugin/package "zbateson/mail-mime-parser ^2.4" is missing or not installed and activated

It works in my test system. Funny. Then I'll probably be able to get by without it for now. I assume it's something to do with the database.
