### ISSUE TITLE
FroshMailArchive muss migriert werden

### ISSUE THREAD

**Issue by 2009triplex** [FriendsOfShopware/FroshPlatformMailArchive#55]
### Please describe the feature you would like to see implemented.

Hallo,

seit dem Shopware update kommt die Meldung das die Mails über CLI mit einem Befehl migriert werden müssen.

Leider bekomme ich das nicht hin, kann man mir helfen und eine kurze Schritt für Schritt Anleitung machen?

Danke

**Comment by tinect** [comment]
Hallo,

dort findest du Informationen zur CLI: https://docs.shopware.com/de/shopware-6-de/tutorials-und-faq/shopware-cli

Stelle auch sicher, dass `messenger:consume` läuft: https://docs.shopware.com/de/shopware-6-de/tutorials-und-faq/message-queue-und-scheduled-tasks?category=shopware-6-de/tutorials-und-faq/allgemeines

Wenn du dazu Support benötigst, findest du sicher auch fähigen Support im Shopware Slack - notfalls im Channel `#job-ads`.
