### ISSUE TITLE
FroshMailArchive must be migrated

### ISSUE THREAD

**Issue by Heddy147** [FriendsOfShopware/FroshPlatformMailArchive#59]
### Question

After updating the plugin to support Shopware 6.5 the message "FroshMailArchive must be migrated" appears everytime after I've logged in.

I have to execute command `bin/console frosh:mailarchive:migrate`. While executing a progress bar appears and everything seems to be right. But the message still appears.

**Comment by shyim** [comment]
is your message queue empty? It just dispatches a lot of queu messages

**Comment by Heddy147** [comment]
How can I check it?
I cleared the notifications. There are no entries in db table "messenger_messages".

I've installed FroshTools and in the tab "Queue Manager" both are on 0

**Comment by marvn-r3** [comment]
On our system it's the same as @Heddy147 explained. 

In my testing enviroment, I cleared the queue via FroshTools but the message still appears each time.

**Comment by cbmod21** [comment]
After migration: where are the email-files stored in file system?
The database still has a large table containing the emails

**Comment by Heddy147** [comment]
@cbmod21 
`files/plugins/frosh_platform_mail_archive/mails`

I claim there are now the emails in there that have been sent since the update.

**Comment by tinect** [comment]
`bin/console frosh:mailarchive:migrate` drops message for the queue for every mail to migrate.

Make sure your `message:consume` is running

**Comment by Heddy147** [comment]
`messenger:consume` is running but it still did not work.

`--strict` is the wrong parameter. With `--help` I found out that `--sync` is the right parameter. It then worked and the message doesn't appear anymore.

Nevertheless, I think there is a bug with working with the queue.

**Comment by tinect** [comment]
Hey @Heddy147 

Thank you for the Feedback. I fixed the option in my message.

**Comment by tinect** [comment]
You have installed the recent version of the plugin?

**Comment by cbmod21** [comment]
bin/console frosh:mailarchive:migrate --sync
seemed to work for me after updating to the latest plugin version

**Comment by tinect** [comment]
I closed here, while the problem has been solved on your systems. If you experience new issue, please open a new issue with infomations:
- are there messages in your queue after you run the command without `--sync`?
- are there any error in your logs?
