### ISSUE TITLE
Can´t install

### ISSUE THREAD

**Issue by pabstflo** [FriendsOfShopware/FroshPlatformMailArchive#62]
### Question

When I try to install the plugin I get following message:
Bad Request

Could not execute "composer require" for plugin "FroshPlatformMailArchive (frosh/mail-platform-archive:2.0.5). Output: ./composer.json has been updated Running composer update frosh/mail-platform-archive --with-dependencies Loading composer repositories with package information Dependency shopware/core is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies. Updating dependencies Lock file operations: 6 installs, 0 updates, 0 removals - Locking frosh/mail-platform-archive (2.0.5) - Locking pimple/pimple (v3.5.0) - Locking symfony/polyfill-iconv (v1.28.0) - Locking zbateson/mail-mime-parser (2.4.0) - Locking zbateson/mb-wrapper (1.2.0) - Locking zbateson/stream-decorators (1.2.1) Writing lock file Installing dependencies from lock file (including require-dev) Package operations: 6 installs, 0 updates, 0 removals As there is no 'unzip' nor '7z' command installed zip files are being unpacked using the PHP zip extension. This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost. Installing 'unzip' or '7z' (21.01+) may remediate them. 0 [>---------------------------] 0 [->--------------------------] - Installing symfony/polyfill-iconv (v1.28.0): Extracting archive - Installing zbateson/mb-wrapper (1.2.0): Extracting archive - Installing zbateson/stream-decorators (1.2.1): Extracting archive - Installing pimple/pimple (v3.5.0): Extracting archive - Installing zbateson/mail-mime-parser (2.4.0): Extracting archive - Installing frosh/mail-platform-archive (2.0.5): Symlinking from custom/plugins/FroshPlatformMailArchive 0 [>---------------------------] 0 [->--------------------------] Generating optimized autoload files 144 packages you are using are looking for funding. Use the `composer fund` command to find out more! Run composer recipes at any time to see the status of your Symfony recipes. Found 1 security vulnerability advisory affecting 1 package. Run "composer audit" for a full list of advisories.

**Comment by tinect** [comment]
Please describe the steps you performed to install the plugin.

It looks like you uploaded a recent plugin to a Shopware lower than 6.5.

**Comment by tinect** [comment]
I'll close here due to inactivity
