### ISSUE TITLE
Increase subject field length restriction

### ISSUE THREAD

**Issue by RafaelKr** [FriendsOfShopware/FroshPlatformMailArchive#68]
### Please describe the feature you would like to see implemented.

We're sending some mails for error reporting, sometimes the Subject exceeds the 255 character limit of the subject column.
I now manually set it to data type `TEXT` (limit of 65,535 characters) in our database.

**Comment by shyim** [comment]
Do you want to create a PR? the rfc says 998 chars, I would create then a varchar(998)
