### ISSUE TITLE
Anzeigen doesn't work anymore

### ISSUE THREAD

**Issue by viktor-franz** [FriendsOfShopware/FroshPlatformMailArchive#7]
Hello, we are running Shopware 6.2.2 but with the latest Update of your Plugin the button "anzeigen" doesn't work anymore. Can you please check? Thank you for the great Plugin!

**Comment by viktor-franz** [comment]
Hello, do you already have a Feedback? Thank you 👍

**Comment by viktor-franz** [comment]
Hello Guys, are you planning to fix this problem? Thank you a lot :)

**Comment by shyim** [comment]
![image](https://user-images.githubusercontent.com/6224096/90984480-84ca3480-e575-11ea-88c1-85aad3d342fc.png)
I don't see any issues 🙈

**Comment by viktor-franz** [comment]
Hmm, I use 6.2.2
Since the update it doesn‘t work anymore. I‘ll try to uninstall completely and reinstall it.

**Comment by shyim** [comment]
The latest update is only for 6.3 🤔

**Comment by viktor-franz** [comment]
Ok, thank you. Strange that I was able to update the plugin anyways. So I‘ll update shopware and then test. Thank you. Best viktor

**Comment by shyim** [comment]
Okay. I will close this issue then until your feedback :)
