### ISSUE TITLE
Return-Path header makes it impossible to resend email

### ISSUE THREAD

**Issue by hahrens** [FriendsOfShopware/FroshPlatformMailArchive#70]
### PHP Version

8.2.x

### Shopware Version

6.5.x

### Plugin Version

2.0.6, but later version uses the same code

### Actual behaviour

An existing return path header leads to a 500 error when resending the mail via the MailArchive-Plugin, because the Return-Path-Data extracted from EML is an Array (of [Address](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Mime/Address.php)-Instances), but the Header in Symfony mailer requires that to be a Address-Instance or string.

Error-Message: Symfony\\Component\\Mime\\Header\\Headers::addPathHeader(): Argument # 2 ($path) must be of type Symfony\\Component\\Mime\\Address|string, array given, called in [....]/vendor/symfony/mime/Header/Headers.php on line 152

I already digged deeper and think/know that this is a very special case involving multiple packages. According to [rfc2822](https://datatracker.ietf.org/doc/html/rfc2822#section-3.6.7) i think there's no specification about how many addresses the return-path header can contain, but i think more than 1 item doesn't make sense.

The [mail-mime-parser](https://github.com/zbateson/mail-mime-parser) package, which is used here, return an AddressHeader when parsing the eml which is always an array. Sure, the content in the return-path is/should be an address, but FroshPlatformMailArchive passes that array directly to Symfony's [addHeader](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Mime/Header/Headers.php#L138)-Method, there it is passed to [addPathHeader](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/Mime/Header/Headers.php#L106) which requires 2nd argument to be a string.

So i'm a bit unsure where i have to report the issue since so many packages are involved. But since i have the error here, i think that's a start :D

### Expected behaviour

Return-Path should be handled correctly

### Steps to Reproduce?

Shopware by default does not set the Return-Path header. I've set that together with a custom Reply-To-Header in an Event-Listener, because we're sending our mails through a proxy from a no_reply address.

To reproduce, you need to set the Return-Path header for a mail. Here the relevant part of my event listener code:

Theme/src/Resources/config/services.xml
```xml
<?xml version="1.0" ?>

<container xmlns="http://symfony.com/schema/dic/services"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://symfony.com/schema/dic/services http://symfony.com/schema/dic/services/services-1.0.xsd">

    <services>
        <service id="Vendor\Theme\Subscriber\MailSubscriber">
            <tag name="kernel.event_subscriber"/>
        </service>
    </services>
</container>
```

Theme/src/Subscriber/MailSubscriber.php
```php
<?php
namespace Vendor\Theme\Subscriber;

use Shopware\Core\Content\MailTemplate\Service\Event\MailBeforeSentEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Mime\Address;

class MailSubscriber implements EventSubscriberInterface {
    public static function getSubscribedEvents(): array
    {
        return [
            MailBeforeSentEvent::class => 'onMailBeforeSentEvent'
        ];
    }

    public function onMailBeforeSentEvent(MailBeforeSentEvent $event)
    {
        $mail = $event->getMessage();
        $mail->returnPath(new Address("my-custom-return-path@example.com"));

        // in my code i used the return path together with reply-to, if that's relevant
        $mail->addReplyTo(new Address("my-custom-return-path@example.com"));
    }
}
```

Then send an e-mail. I used the template mail test function in Shopware (Settings > Mail Templates) for this.
The email is sent and stored in the Mail-Archive.

After that open the mail archive and try to re-send the mail. This will trigger a 500 error [here](https://github.com/FriendsOfShopware/FroshPlatformMailArchive/blob/main/src/Controller/Api/MailArchiveController.php#L208). I've described more error details above.

**Comment by hahrens** [comment]
A possible solution (if you want to solve that) would be to treat the Return-Path header special, like this 
```php
            if ($header->getName() === 'Return-Path') {
                $headerValue = array_pop($headerValue);
            }
```
in `src/Controller/Api/MailArchiveController.php::enrichFromEml` (line 210, directly below the Content-Type-Check) to only pass the first array-item to the addHeader method.

**Comment by tinect** [comment]
@hahrens would you like to create a PR?

**Comment by hahrens** [comment]
sure, pr #73
