### ISSUE TITLE
Mail sending problem

### ISSUE THREAD

**Issue by akadirkocak** [FriendsOfShopware/FroshPlatformMailArchive#71]
### Question

Hello, we have an online store with Shopware 6 installed. Here, the mails appear in the Mail Archive plugin, but no mail is sent to the user. I checked all settings, SMTP etc. everything is correct. I have been looking for a solution for about 2 months. Can you please help me with this?

**Comment by tinect** [comment]
You might want to check the community slack to look for help regarding your issue.
