### ISSUE TITLE
Fehler nach Shopware Commercial Update

### ISSUE THREAD

**Issue by Transwatt** [FriendsOfShopware/FroshPlatformMailArchive#81]
### Question

Hello, after I tried to install the faulty commercial plugin (on Tuesday) I got the following error message in your mail archive:

Could not execute "composer require" for plugin "FroshPlatformMailArchive (frosh/mail-platform-archive:2.0.7). Output: ./composer.json has been updated Running composer update frosh/mail-platform-archive --with-dependencies Loading composer repositories with package information Dependency shopware/core is also a root requirement. Package has not been listed as an update argument, so keeping locked at old version. Use --with-all-dependencies (-W) to include root dependencies. Cannot create cache directory /www/htdocs/w01749aa/neu.shop.transwatt.de/var/cache/composer/cache/repo/https---repo.packagist.org/, or directory is not writable. Proceeding without cache. See also cache-read-only config if your filesystem is read-only. Updating dependencies Your requirements could not be resolved to an installable set of packages. Problem 1 - Root composer.json requires moorl/foundation 1.5.39 (exact version match: 1.5.39 or 1.5.39.0), found moorl/foundation[1.5.40] but it does not match your constraint and is therefore not installable. Make sure you fix the constraint as packages installed from symlinked path repos are updated even in partial updates and the one from the lock file can thus not be used. Installation failed, reverting ./composer.json and ./composer.lock to their original content.

Unfortunately, uninstalling and reinstalling is not possible either.

What can I do?

Best regards

Mikuteit

**Comment by tinect** [comment]
Hi @Transwatt,

The error seems unrelated to FroshPlatformMailArchive.
Regarding the exception you might need to update your constraint for moorl/foundation in composer.json, while it says you require 1.5.39, but 1.5.40 has been found

**Comment by Transwatt** [comment]
Thanks!
