### ISSUE TITLE
BCC and CC adresses

### ISSUE THREAD

**Issue by henryhildebrandt** [FriendsOfShopware/FroshPlatformMailArchive#93]
Currently the Mail Archive Plugin does not log BCC (Blind Carbon Copy) and CC (Carbon Copy) addresses. This functionality would be very beneficial for our workflow, as it helps to keep track of all recipients involved in communication.

**Comment by tinect** [comment]
What version are you running?

Could you please verify it is not saved in the downloadable "eml"?
