### ISSUE TITLE
You cannot send an email to a changed email address

### ISSUE THREAD

**Issue by gamerlion7** [FriendsOfShopware/FroshPlatformMailArchive#94]
### Actual behaviour

You change an email address, because it is wrong.

Then you want to send the order confirmation to the customer, because he did not get it, but the email is sent to the wrong email address.

### Expected behaviour

You change an email address, because it is wrong.

Then you want to send the order confirmation to the customer, because he did not get it. The customer gets the order confirmation.

### Steps to Reproduce?

You change an email address and click the button "E-Mail erneut senden".

**Comment by tinect** [comment]
the mail is just sent as it was - to the same email address.

The plugin is a archive, not a client. That means it works as expected.

To solve your problem, download the eml and send it manually with your client.

**Comment by gamerlion7** [comment]
How can you download the eml in Shopware?
