### ISSUE TITLE
database still filled after migration

### ISSUE THREAD

**Issue by cbmod21** [FriendsOfShopware/FroshPlatformMailArchive#98]
### Question

we updated from shopware 6.4. to 6.5.
after migrating the frosh mail plugin "frosh:mailarchive:migrate --sync" we hoped the database entries in table "frosh_mail-Archive" are gone.
but the table still is 72MB.

how to fix this?

**Comment by tinect** [comment]
Sure, the database is filled with data, but not with the entire EML, is it? The HTML is currently also saved, but we are thinking of changing it, too.
But there is no issue so far. 

Why is it an issue for you to have a table with 72 MB?

**Comment by cbmod21** [comment]
thanks for the fast answer.
there is no real problem, but we did not see any shrinking of database table after migration.
we hoped that the migration would free up space in our database since the frosh_mail_archive is the biggest table in our shop.
the smaller the database, the faster are dumps etc.

**Comment by shyim** [comment]
I would ignore for the dumps the table :)

**Comment by tinect** [comment]
Is your message consumer running? they are migrated by the messenger. you can verify the eml column is empty.

**Comment by cbmod21** [comment]
the eml column is indeed empty
